# Intended for development and testing purposes only.

services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    hostname: projectify-db
    environment:
      POSTGRES_USER: projectify
      POSTGRES_PASSWORD: projectify
      POSTGRES_DB: projectify
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    hostname: projectify-adminer
    restart: always
    ports:
      - 3100:8080

volumes:
  postgres_data:
