name: Vulnerable action workflow

on:
  pull_request_target:
    branches:
      - main

jobs:
  vulnerable-action-job:
    runs-on: ubuntu-latest
    env:
      MYENV: ${{ secrets.GITHUB_TOKEN}}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - run: |
          echo "--"
          echo $MYENV 
          echo "--"


